steps:
  # NPM Install
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  # NPM Install Functions
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'postinstall']
  # Build
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
