steps:
  # NPM Install
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  # Test
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test']
    env: [
      "REACT_APP_FIREBASE_API_KEY=${_FIREBASE_API_KEY}",
      "REACT_APP_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}",
      "REACT_APP_FIREBASE_DATABASE_URL=${_FIREBASE_DATABASE_URL}",
      "REACT_APP_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}",
      "REACT_APP_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}",
      "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}",
    ]
substitutions:
  _FIREBASE_API_KEY: 'AIzaSyAYz_uL2DyMYggJk7EC9PZ93iQyOGLU4ZE'
  _FIREBASE_AUTH_DOMAIN: 'webchat-analytics.firebaseapp.com'
  _FIREBASE_DATABASE_URL: 'https://webchat-analytics.firebaseio.com'
  _FIREBASE_PROJECT_ID: 'webchat-analytics'
  _FIREBASE_STORAGE_BUCKET: 'webchat-analytics.appspot.com'
  _FIREBASE_MESSAGING_SENDER_ID: '338284905017'
options:
  substitution_option: 'ALLOW_LOOSE'