export const UPDATE_FILTERS = 'UPDATE_FILTERS_DATE_RANGE'
export const UPDATE_FEEDBACK_TYPE = 'UPDATE_FEEDBACK_TYPE'
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS'

export const FETCH_CONVERSATIONS_START = 'FETCH_CONVERSATIONS_START'
export const FETCH_CONVERSATIONS_SUCCESS = 'FETCH_CONVERSATIONS_SUCCESS'
export const FETCH_CONVERSATIONS_FAIL = 'FETCH_CONVERSATIONS_FAIL'

export const FETCH_METRICS_START = 'FETCH_METRICS_START'
export const FETCH_METRICS_SUCCESS = 'FETCH_METRICS_SUCCESS'
export const FETCH_METRICS_FAIL = 'FETCH_METRICS_FAIL'

export const FETCH_PROJECTS_START = 'FETCH_PROJECTS_START'
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS'
export const FETCH_PROJECTS_FAIL = 'FETCH_PROJECTS_FAIL'
