export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAIL = 'SIGNIN_FAIL'
export const SIGNOUT_USER = 'SIGNOUT_USER'
export const SIGNIN_START = 'SIGNIN_START'
export const FETCH_USER = 'FETCH_USER'

export const TOGGLE_CONFIG_LOADING = 'TOGGLE_CONFIG_LOADING'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR'

export const UPDATE_FILTERS = 'UPDATE_FILTERS_DATE_RANGE'
export const UPDATE_FEEDBACK_TYPE = 'UPDATE_FEEDBACK_TYPE'
export const UPDATE_CONTEXT = 'UPDATE_CONTEXT'
export const UPDATE_EXPORT_DATE = 'UPDATE_EXPORT_DATE'
export const TOGGLE_SETTINGS = 'TOGGLE_SETTINGS'

export const DOWNLOAD_EXPORT = 'DOWNLOAD_EXPORT'

export const FETCH_CONVERSATIONS_START = 'FETCH_CONVERSATIONS_START'
export const FETCH_CONVERSATIONS_SUCCESS = 'FETCH_CONVERSATIONS_SUCCESS'
export const FETCH_CONVERSATIONS_FAIL = 'FETCH_CONVERSATIONS_FAIL'

export const FETCH_METRICS_START = 'FETCH_METRICS_START'
export const FETCH_METRICS_SUCCESS = 'FETCH_METRICS_SUCCESS'
export const FETCH_METRICS_FAIL = 'FETCH_METRICS_FAIL'

export const FETCH_PROJECTS_START = 'FETCH_PROJECTS_START'
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS'
export const FETCH_PROJECTS_FAIL = 'FETCH_PROJECTS_FAIL'
