version: 2
jobs:
  test_analytics:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo/
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run postinstall
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: 'Add env variables & test'
          command: |
            export REACT_APP_FIREBASE_API_KEY=$FIREBASE_API_KEY
            export REACT_APP_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
            export REACT_APP_FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL
            export REACT_APP_FIREBASE_DEPLOY_TOKEN=$FIREBASE_DEPLOY_TOKEN
            export REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
            export REACT_APP_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
            export REACT_APP_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
            npm run test
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - node_modules
            - package.json
            - firebase.json
            - .firebaserc
  deploy_analytics:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo/
    steps:
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: 'Add env variables & build'
          command: |
            export REACT_APP_FIREBASE_API_KEY=$FIREBASE_API_KEY
            export REACT_APP_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
            export REACT_APP_FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL
            export REACT_APP_FIREBASE_DEPLOY_TOKEN=$FIREBASE_DEPLOY_TOKEN
            export REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
            export REACT_APP_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
            export REACT_APP_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
            CI=false npm run build
      - run: npm install --save-dev firebase-tools
      - run: firebase deploy -P $FIREBASE_PROJECT_ID --only functions,hosting --token $FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  build_deploy:
    jobs:
      - test_analytics
      - deploy_analytics:
          requires:
            - test_analytics
          filters:
            branches:
              only:
                - development
