version: 2
jobs:
  test_analytics:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo/
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm install
      - run: npm run postinstall
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - node_modules
            - functions/node_modules
      - run:
          name: 'Add env variables & test'
          command: |
            export REACT_APP_FIREBASE_API_KEY=$FIREBASE_API_KEY
            export REACT_APP_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
            export REACT_APP_FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL
            export REACT_APP_FIREBASE_DEPLOY_TOKEN=$FIREBASE_DEPLOY_TOKEN
            export REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
            export REACT_APP_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
            export REACT_APP_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET

  deploy_analytics:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo/
    steps:
      - checkout
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: 'Add env variables & build'
          command: |
            export REACT_APP_FIREBASE_API_KEY=$FIREBASE_API_KEY
            export REACT_APP_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
            export REACT_APP_FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL
            export REACT_APP_FIREBASE_DEPLOY_TOKEN=$FIREBASE_DEPLOY_TOKEN
            export REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
            export REACT_APP_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
            export REACT_APP_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
            export REACT_APP_DOWNLOAD_EXPORT_FUNCTION_URL=$DOWNLOAD_EXPORT_FUNCTION_URL
            CI=false npm run build
      - run:
          name: 'Create env file for functions'
          command: cd functions && echo
            "GCS_PROJECT_ID=${GCS_PROJECT_ID}

            GCS_CLIENT_EMAIL=${GCS_CLIENT_EMAIL}

            GCS_PRIVATE_KEY=${GCS_PRIVATE_KEY}

            AUTOML_CLIENT_EMAIL=${AUTOML_CLIENT_EMAIL}" > .env

      - run: sudo npm install -g firebase-tools
      - run: firebase -P $FIREBASE_PROJECT_ID --token $FIREBASE_DEPLOY_TOKEN functions:config:set gcs.project_id=$GCS_PROJECT_ID gcs.client_email=$GCS_CLIENT_EMAIL gcs.private_key="$GCS_PRIVATE_KEY"
      - run: firebase deploy -P $FIREBASE_PROJECT_ID --only functions,hosting --token $FIREBASE_DEPLOY_TOKEN
  deploy_stage_analytics:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo/
    steps:
      - checkout
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: 'Add env variables & build'
          command: |
            export REACT_APP_FIREBASE_API_KEY=$FIREBASE_API_KEY
            export REACT_APP_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
            export REACT_APP_FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL
            export REACT_APP_FIREBASE_DEPLOY_TOKEN=$FIREBASE_DEPLOY_TOKEN
            export REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
            export REACT_APP_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
            export REACT_APP_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
            export REACT_APP_DOWNLOAD_EXPORT_FUNCTION_URL=$DOWNLOAD_EXPORT_FUNCTION_URL
            CI=false npm run build
      - run:
          name: 'Create env file for functions'
          command: cd functions && echo
            "GCS_PROJECT_ID=${STAGE_GCS_PROJECT_ID}

            GCS_CLIENT_EMAIL=${STAGE_GCS_CLIENT_EMAIL}

            GCS_PRIVATE_KEY=${STAGE_GCS_PRIVATE_KEY}

            GCS_URI=${STAGE_GCS_URI}

            AGENT_PROJECT=${STAGE_AGENT_PROJECT}

            AGENT_PRIVATE_KEY=${STAGE_AGENT_PRIVATE_KEY}

            AGENT_CLIENT_EMAIL=${STAGE_AGENT_CLIENT_EMAIL}

            AUTOML_PROJECT=${STAGE_AUTOML_PROJECT}

            AUTOML_LOCATION=${STAGE_AUTOML_LOCATION}

            AUTOML_CAT_MODEL=${STAGE_AUTOML_CAT_MODEL}

            AUTOML_DATASET=${STAGE_AUTOML_DATASET}

            AUTOML_PRIVATE_KEY=${STAGE_AUTOML_PRIVATE_KEY}

            AUTOML_CLIENT_EMAIL=${STAGE_AUTOML_CLIENT_EMAIL}" > .env

      - run: sudo npm install -g firebase-tools
      - run: firebase deploy -P $STAGE_FIREBASE_PROJECT_ID --only functions --token $STAGE_FIREBASE_DEPLOY_TOKEN
  deploy_dev_analytics:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo/
    steps:
      - checkout
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: 'Add env variables & build'
          command: |
            export REACT_APP_FIREBASE_API_KEY=$FIREBASE_API_KEY
            export REACT_APP_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
            export REACT_APP_FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL
            export REACT_APP_FIREBASE_DEPLOY_TOKEN=$FIREBASE_DEPLOY_TOKEN
            export REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
            export REACT_APP_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
            export REACT_APP_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
            export REACT_APP_DOWNLOAD_EXPORT_FUNCTION_URL=$DOWNLOAD_EXPORT_FUNCTION_URL
            CI=false npm run build
      - run:
          name: 'Create env file for functions'
          command: cd functions && echo
            "GCS_PROJECT_ID=${DEV_GCS_PROJECT_ID}

            GCS_CLIENT_EMAIL=${DEV_GCS_CLIENT_EMAIL}

            GCS_PRIVATE_KEY=${DEV_GCS_PRIVATE_KEY}

            GCS_URI=${DEV_GCS_URI}

            AGENT_PROJECT=${DEV_AGENT_PROJECT}

            AGENT_PRIVATE_KEY=${DEV_AGENT_PRIVATE_KEY}

            AGENT_CLIENT_EMAIL=${DEV_AGENT_CLIENT_EMAIL}

            AUTOML_PROJECT=${DEV_AUTOML_PROJECT}

            AUTOML_LOCATION=${DEV_AUTOML_LOCATION}

            AUTOML_CAT_MODEL=${DEV_AUTOML_CAT_MODEL}

            AUTOML_DATASET=${DEV_AUTOML_DATASET}

            AUTOML_PRIVATE_KEY=${DEV_AUTOML_PRIVATE_KEY}

            AUTOML_CLIENT_EMAIL=${DEV_AUTOML_CLIENT_EMAIL}" > .env

      - run: sudo npm install -g firebase-tools
      - run: firebase deploy -P $DEV_FIREBASE_PROJECT_ID --only functions --token $DEV_FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  build_deploy:
    jobs:
      - test_analytics
      - deploy_analytics:
          requires:
            - test_analytics
          filters:
            branches:
              only:
                - master
      - deploy_stage_analytics:
          requires:
            - test_analytics
          filters:
            branches:
              only:
                - stage
      - deploy_dev_analytics:
          requires:
            - test_analytics
          filters:
            branches:
              only:
                - development      
