version: 2.1
jobs:
  deploy_analytics:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo/
    parameters:
      gcsProjectId:
        type: string
      gcsClientEmail:
        type: string
      gcsPrivateKey:
        type: string
      gcsUri:
        type: string
      agentProject:
        type: string
      agentPrivateKey:
        type: string
      agentClientEmail:
        type: string
      autoMlProject:
        type: string
      autoMlLocation:
        type: string
      autoMlDataset:
        type: string
      firebaseApiKey:
        type: string
      firebaseAuthDomain:
        type: string
      firebaseDatabaseUrl:
        type: string
      firebaseDeployToken:
        type: string
      firebaseMessagingSenderId:
        type: string
      firebaseProjectId:
        type: string
      firebaseStorageBucket:
        type: string
      firebaseAppId:
        type: string
      downloadExportUrl:
        type: string
      mdhsKeyJson:
        type: string
    steps:
      - checkout
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm install
      - run: npm run postinstall
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - node_modules
            - functions/node_modules
      - run:
          name: "Add env variables & build"
          command: |
            export REACT_APP_FIREBASE_API_KEY=${<< parameters.firebaseApiKey >>}
            export REACT_APP_FIREBASE_AUTH_DOMAIN=${<< parameters.firebaseAuthDomain >>}
            export REACT_APP_FIREBASE_DATABASE_URL=${<< parameters.firebaseDatabaseUrl >>}
            export REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${<< parameters.firebaseMessagingSenderId >>}
            export REACT_APP_FIREBASE_PROJECT_ID=${<< parameters.firebaseProjectId >>}
            export REACT_APP_FIREBASE_STORAGE_BUCKET=${<< parameters.firebaseStorageBucket >>}
            export REACT_APP_FIREBASE_APP_ID=${<< parameters.firebaseAppId >>}
            export REACT_APP_DOWNLOAD_EXPORT_FUNCTION_URL=${<< parameters.downloadExportUrl >>}
            CI=false npm run build
      - run:
          name: "Create env file for functions"
          command: cd functions && echo
            "GCS_PROJECT_ID=${<< parameters.gcsProjectId >>}

            GCS_CLIENT_EMAIL=${<< parameters.gcsClientEmail >>}

            GCS_PRIVATE_KEY=${<< parameters.gcsPrivateKey >>}

            MDHS_GCS_URI=${<< parameters.gcsUri >>}

            AGENT_PROJECT=${<< parameters.agentProject >>}

            AGENT_PRIVATE_KEY=${<< parameters.agentPrivateKey >>}

            AGENT_CLIENT_EMAIL=${<< parameters.agentClientEmail >>}

            AUTOML_MDHS_PROJECT_ID=${<< parameters.autoMlProject >>}

            AUTOML_LOCATION=${<< parameters.autoMlLocation >>}

            AUTOML_MDHS_DATASET_ID=${<< parameters.autoMlDataset >>}" > .env

      - run:
          name: "Create mdhs key file for functions"
          command: cd functions && echo "${<< parameters.mdhsKeyJson >>}" > mdhs-key.json

      - run: sudo npm install -g firebase-tools
      - run: firebase deploy -P ${<< parameters.firebaseProjectId >>} --only functions,hosting,database,firestore  --token ${<< parameters.firebaseDeployToken >>}
workflows:
  version: 2
  build_deploy:
    jobs:
      - deploy_analytics:
          gcsProjectId: PROD_GCS_PROJECT_ID
          gcsClientEmail: PROD_GCS_CLIENT_EMAIL
          gcsPrivateKey: PROD_GCS_PRIVATE_KEY
          gcsUri: PROD_MDHS_GCS_URI
          agentProject: PROD_AGENT_PROJECT
          agentPrivateKey: PROD_AGENT_PRIVATE_KEY
          agentClientEmail: PROD_AGENT_CLIENT_EMAIL
          autoMlProject: PROD_AUTOML_MDHS_PROJECT_ID
          autoMlLocation: PROD_AUTOML_LOCATION
          autoMlDataset: PROD_AUTOML_MDHS_DATASET_ID
          firebaseApiKey: PROD_FIREBASE_API_KEY
          firebaseAuthDomain: PROD_FIREBASE_AUTH_DOMAIN
          firebaseDatabaseUrl: PROD_FIREBASE_DATABASE_URL
          firebaseDeployToken: PROD_FIREBASE_DEPLOY_TOKEN
          firebaseMessagingSenderId: PROD_FIREBASE_MESSAGING_SENDER_ID
          firebaseProjectId: PROD_FIREBASE_PROJECT_ID
          firebaseStorageBucket: PROD_FIREBASE_STORAGE_BUCKET
          firebaseAppId: PROD_FIREBASE_APP_ID
          downloadExportUrl: PROD_DOWNLOAD_EXPORT_FUNCTION_URL
          mdhsKeyJson: PROD_MDHS_KEY_JSON
          filters:
            branches:
              only:
                - master
      - deploy_analytics:
          gcsProjectId: STAGE_GCS_PROJECT_ID
          gcsClientEmail: STAGE_GCS_CLIENT_EMAIL
          gcsPrivateKey: STAGE_GCS_PRIVATE_KEY
          gcsUri: STAGE_MDHS_GCS_URI
          agentProject: STAGE_AGENT_PROJECT
          agentPrivateKey: STAGE_AGENT_PRIVATE_KEY
          agentClientEmail: STAGE_AGENT_CLIENT_EMAIL
          autoMlProject: STAGE_AUTOML_MDHS_PROJECT_ID
          autoMlLocation: STAGE_AUTOML_LOCATION
          autoMlDataset: STAGE_AUTOML_MDHS_DATASET_ID
          firebaseApiKey: STAGE_FIREBASE_API_KEY
          firebaseAuthDomain: STAGE_FIREBASE_AUTH_DOMAIN
          firebaseDatabaseUrl: STAGE_FIREBASE_DATABASE_URL
          firebaseDeployToken: STAGE_FIREBASE_DEPLOY_TOKEN
          firebaseMessagingSenderId: STAGE_FIREBASE_MESSAGING_SENDER_ID
          firebaseProjectId: STAGE_FIREBASE_PROJECT_ID
          firebaseStorageBucket: STAGE_FIREBASE_STORAGE_BUCKET
          firebaseAppId: STAGE_FIREBASE_APP_ID
          downloadExportUrl: STAGE_DOWNLOAD_EXPORT_FUNCTION_URL
          mdhsKeyJson: STAGE_MDHS_KEY_JSON
          filters:
            branches:
              only:
                - stage
      - deploy_analytics:
          gcsProjectId: ISD_GCS_PROJECT_ID
          gcsClientEmail: ISD_GCS_CLIENT_EMAIL
          gcsPrivateKey: ISD_GCS_PRIVATE_KEY
          gcsUri: ISD_MDHS_GCS_URI
          agentProject: ISD_AGENT_PROJECT
          agentPrivateKey: ISD_AGENT_PRIVATE_KEY
          agentClientEmail: ISD_AGENT_CLIENT_EMAIL
          autoMlProject: ISD_AUTOML_MDHS_PROJECT_ID
          autoMlLocation: ISD_AUTOML_LOCATION
          autoMlDataset: ISD_AUTOML_MDHS_DATASET_ID
          firebaseApiKey: ISD_FIREBASE_API_KEY
          firebaseAuthDomain: ISD_FIREBASE_AUTH_DOMAIN
          firebaseDatabaseUrl: ISD_FIREBASE_DATABASE_URL
          firebaseDeployToken: DEV_FIREBASE_DEPLOY_TOKEN
          firebaseMessagingSenderId: ISD_FIREBASE_MESSAGING_SENDER_ID
          firebaseProjectId: ISD_FIREBASE_PROJECT_ID
          firebaseStorageBucket: ISD_FIREBASE_STORAGE_BUCKET
          firebaseAppId: ISD_FIREBASE_APP_ID
          downloadExportUrl: ISD_DOWNLOAD_EXPORT_FUNCTION_URL
          mdhsKeyJson: ISD_MDHS_KEY_JSON
          filters:
            branches:
              only:
                - isd
      - deploy_analytics:
          gcsProjectId: DEV_GCS_PROJECT_ID
          gcsClientEmail: DEV_GCS_CLIENT_EMAIL
          gcsPrivateKey: DEV_GCS_PRIVATE_KEY
          gcsUri: DEV_MDHS_GCS_URI
          agentProject: DEV_AGENT_PROJECT
          agentPrivateKey: DEV_AGENT_PRIVATE_KEY
          agentClientEmail: DEV_AGENT_CLIENT_EMAIL
          autoMlProject: DEV_AUTOML_MDHS_PROJECT_ID
          autoMlLocation: DEV_AUTOML_LOCATION
          autoMlDataset: DEV_AUTOML_MDHS_DATASET_ID
          firebaseApiKey: DEV_FIREBASE_API_KEY
          firebaseAuthDomain: DEV_FIREBASE_AUTH_DOMAIN
          firebaseDatabaseUrl: DEV_FIREBASE_DATABASE_URL
          firebaseDeployToken: DEV_FIREBASE_DEPLOY_TOKEN
          firebaseMessagingSenderId: DEV_FIREBASE_MESSAGING_SENDER_ID
          firebaseProjectId: DEV_FIREBASE_PROJECT_ID
          firebaseStorageBucket: DEV_FIREBASE_STORAGE_BUCKET
          firebaseAppId: DEV_FIREBASE_APP_ID
          downloadExportUrl: DEV_DOWNLOAD_EXPORT_FUNCTION_URL
          mdhsKeyJson: DEV_MDHS_KEY_JSON
          filters:
            branches:
              only:
                - development
